services:
  - type: web
    name: blockscan-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        generateValue: false
      - key: MONGO_URI
        generateValue: false
      - key: NOWPAYMENTS_API_KEY
        generateValue: false
      - key: NOWPAYMENTS_IPN_SECRET
        generateValue: false
      - key: OPENROUTER_API_KEY
        generateValue: false
