services:
  - type: worker
    name: blockscan-ai-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      MONGO_URI: ${MONGO_URI}
      CLUSTER_NAME: ${CLUSTER_NAME}
